{% set name = "modelx" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modelx-{{ version }}.tar.gz
  sha256: a5e8aa936e78a014547d93e6068b251187b5a98b7a289b3bbe7e071a022aea58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - networkx >=2.0
    - python >=3.6
    - libcst

test:
  imports:
    - modelx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fumitoh/modelx
  summary: Numerical computing tool to use Python like a spreadsheet
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
