{% set name = "modelx" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modelx-{{ version }}.tar.gz
  sha256: 2fe8bc01bf99c06916ed5c3ddc167a9894f8003a59314a6b59e657e884c05fd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - networkx >=2.0
    - python >=3.6

test:
  imports:
    - modelx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fumitoh/modelx
  summary: Numerical computing tool to use Python like a spreadsheet
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
