{% set name = "modelx" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modelx-{{ version }}.tar.gz
  sha256: cb8871eb8e3f8782a899efa0f18312121d771d7c637ed68ab40718a7b6cd7020

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - networkx >=2.0
    - python >=3.6

test:
  imports:
    - modelx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fumitoh/modelx
  summary: Numerical computing tool to use Python like a spreadsheet
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
