{% set name = "modelx" %}
{% set version = "0.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/modelx-{{ version }}.tar.gz
  sha256: 66b6901c3eac34a97e50150d968bb6c46d972b2c54b0b29bff3dd564c8f005ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - asttokens
    - networkx >=2.0
    - python >={{ python_min }}
    - libcst

test:
  imports:
    - modelx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fumitoh/modelx
  summary: Numerical computing tool to use Python like a spreadsheet
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
