{% set name = "modelx" %}
{% set version = "0.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/modelx-{{ version }}.tar.gz
  sha256: f64668473d1108cc56d38ab1ba38971065aa41cf4b4b7ca72fd5684eda6e2799

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - asttokens
    - networkx >=2.0
    - python >={{ python_min }}
    - libcst

test:
  imports:
    - modelx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fumitoh/modelx
  summary: Numerical computing tool to use Python like a spreadsheet
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
